
version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /home/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "./manage.py migrate
      && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/srv
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=put_in_good_hands_project.settings_docker