# Generated by Django 3.2.3 on 2021-05-31 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import put_in_good_hands_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(0, 'fundacja'), (1, 'organizacja pozarządowa'), (2, 'zbiórka lokalna')], default=(0, 'fundacja'))),
                ('categories', models.ManyToManyField(to='put_in_good_hands_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255, validators=[put_in_good_hands_app.validators.validate_address])),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(help_text='XX-XXX', max_length=6, validators=[put_in_good_hands_app.validators.validate_zip_code])),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='put_in_good_hands_app.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='put_in_good_hands_app.institution')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
