# Generated by Django 3.2.3 on 2021-06-17 14:23

from django.db import migrations, models
import put_in_good_hands_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('put_in_good_hands_app', '0002_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=128, validators=[put_in_good_hands_app.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(validators=[put_in_good_hands_app.validators.validate_pick_up_date]),
        ),
    ]
